package engine

import (
	"strings"
	"testing"
)

func makeMinimalReport() *FullReport {
	return &FullReport{
		SimulationID: "test-123",
		Question:     "What if a major competitor launches a free tier?",
		ProbableFuture: ProbableFuture{
			Narrative:  "The market will fragment significantly over the next 18 months.",
			Confidence: 0.72,
			Timeline: []TimelineEntry{
				{Horizon: "6 months", Description: "Early adopters migrate", Confidence: 0.8},
				{Horizon: "12 months", Description: "Pricing pressure peaks", Confidence: 0.65},
			},
			KeyAssumptions: []string{"Competitor has sufficient runway", "Enterprise segment holds"},
		},
		TensionMap: []TensionEntry{
			{RuleID: "pricing", Description: "Premium pricing model", Domain: "market", Tension: 0.85, Color: "red"},
		},
		RuptureScenarios: []RuptureScenario{
			{
				RuleID:          "pricing",
				RuleDescription: "Premium pricing collapses",
				Probability:     0.68,
				WhoBreaks:       "New entrant",
				HowItHappens:    "Launches freemium at scale",
				ImpactOnCompany: "30% ARR at risk",
				HowToBeFirst:    "Build switching costs now",
			},
		},
		FractureEvents: []FractureEvent{
			{
				Round:      5,
				ProposedBy: "disruptor-agent-1",
				Proposal:   RuleProposal{OriginalRuleID: "pricing", NewDescription: "Open-source core released"},
				Accepted:   true,
				Confidence: 0.75,
			},
		},
		TotalTokens: 12500,
		DurationMs:  45000,
		Watermark: Watermark{
			GeneratedAt: "2026-03-25T10:00:00Z",
			Notice:      "Generated by FRACTURE v2.5.0",
		},
	}
}

func TestReportToMarkdown(t *testing.T) {
	report := makeMinimalReport()
	md := ReportToMarkdown(report)

	sections := []string{
		"# FRACTURE Report",
		"## Probable Future",
		"The market will fragment",
		"**Confidence:** 72%",
		"### Timeline",
		"6 months",
		"### Key Assumptions",
		"Competitor has sufficient runway",
		"## Tension Map",
		"Premium pricing model",
		"## Rupture Scenarios",
		"### Premium pricing collapses",
		"**Probability:** 68%",
		"**How to be first:** Build switching costs now",
		"## Fracture Events",
		"Open-source core released",
		"Generated by FRACTURE v2.5.0",
	}
	for _, want := range sections {
		if !strings.Contains(md, want) {
			t.Errorf("markdown missing section %q", want)
		}
	}
}

func TestReportToMarkdownTableEscaping(t *testing.T) {
	report := makeMinimalReport()
	report.TensionMap = []TensionEntry{
		{RuleID: "r1", Description: "Rule with | pipe and\nnewline", Domain: "market", Tension: 0.5, Color: "yellow"},
	}
	md := ReportToMarkdown(report)
	if strings.Contains(md, "pipe and\nnewline") {
		t.Error("newline in table cell should be escaped to space")
	}
	if strings.Contains(md, "pipe and | pipe") {
		t.Error("pipe in table cell should be escaped")
	}
}

func TestReportToMarkdownEmptyOptionalSections(t *testing.T) {
	report := makeMinimalReport()
	report.Coalitions = nil
	report.RuptureTimeline = nil
	report.ActionPlaybook = nil
	report.EnsembleResult = nil

	md := ReportToMarkdown(report)

	unwanted := []string{"## Coalitions", "## Rupture Timeline", "## Action Playbook", "## Ensemble"}
	for _, section := range unwanted {
		if strings.Contains(md, section) {
			t.Errorf("empty section %q should not appear in markdown", section)
		}
	}
}

func TestReportToMarkdownWithPlaybook(t *testing.T) {
	report := makeMinimalReport()
	report.ActionPlaybook = &ActionPlaybook{
		Horizon90Days:  []string{"Accelerate roadmap", "Lock in key accounts"},
		Horizon1Year:   []string{"Launch enterprise tier"},
		QuickWins:      []string{"Publish comparison page"},
		CriticalRisks:  []string{"Lose SMB segment"},
	}
	md := ReportToMarkdown(report)
	for _, want := range []string{
		"## Action Playbook",
		"### 90 Days",
		"Accelerate roadmap",
		"### 1 Year",
		"### Quick Wins",
		"### Critical Risks",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("playbook markdown missing %q", want)
		}
	}
}

func TestReportToMarkdownWithEnsemble(t *testing.T) {
	report := makeMinimalReport()
	report.EnsembleResult = &EnsembleResult{
		RunCount: 2,
		Consensus: []FractureEvent{
			{Round: 3, Proposal: RuleProposal{NewDescription: "Consensus fracture event"}},
		},
		WeakSignals: []FractureEvent{
			{Round: 7, Proposal: RuleProposal{NewDescription: "Weak signal event"}},
		},
	}
	md := ReportToMarkdown(report)
	for _, want := range []string{
		"## Ensemble",
		"**Runs:** 2",
		"### Consensus",
		"Consensus fracture event",
		"### Weak Signals",
		"Weak signal event",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("ensemble markdown missing %q", want)
		}
	}
}

func TestReportToMarkdownWatermark(t *testing.T) {
	report := makeMinimalReport()
	md := ReportToMarkdown(report)
	if !strings.HasSuffix(strings.TrimSpace(md), "*Generated by FRACTURE v2.5.0*") {
		t.Error("watermark should appear at the end of markdown")
	}
	if !strings.Contains(md, "---") {
		t.Error("horizontal rule separator should precede watermark")
	}
}

func TestReportToHTML(t *testing.T) {
	report := makeMinimalReport()
	report.Question = "What if a major competitor launches a free tier?"
	report.Watermark.Tool = "FRACTURE"
	report.Watermark.Version = "v2.5.0"
	report.Watermark.Notice = "Generated by FRACTURE v2.5.0"
	report.ActionPlaybook = &ActionPlaybook{
		Horizon90Days: []string{"Accelerate roadmap"},
		Horizon1Year:  []string{"Launch enterprise tier"},
		QuickWins:     []string{"Publish comparison page"},
		CriticalRisks: []string{"Lose SMB segment"},
	}
	report.Coalitions = []Coalition{
		{Name: "Enterprise Defenders", AgentNames: []string{"Warren Buffett", "Michael Porter"}, SharedGoal: "Protect margin", Strength: 0.8, IsDisruptive: false},
	}

	doc := ReportToHTML(report, "healthcare")

	mustContain := []string{
		"<!DOCTYPE html>",
		"What if a major competitor launches a free tier?",
		"HEALTHCARE SKILL",
		"Prov",           // Provável Futuro (ã encoded as entity)
		"Tens",           // Mapa de Tensão
		"Playbook",
		"FRACTURE",
		"Generated by FRACTURE v2.5.0",
		"Confian",        // Confiança — ç is an HTML entity in output
		"scenario-card",
		"how-to-be-first",
		"Enterprise Defenders",
	}
	for _, want := range mustContain {
		if !strings.Contains(doc, want) {
			t.Errorf("HTML missing expected content: %q", want)
		}
	}

	// XSS protection: script tags must not appear
	if strings.Contains(doc, "<script") {
		t.Error("HTML output must not contain <script tags")
	}

	// XSS: injected strings must be escaped
	report2 := makeMinimalReport()
	report2.Question = `<script>alert('xss')</script>`
	// Injection attempt that would break out of a tag attribute context if unescaped
	report2.ProbableFuture.Narrative = `"><img src=x onerror=alert(1)>`
	doc2 := ReportToHTML(report2, "")
	if strings.Contains(doc2, "<script>alert") {
		t.Error("XSS: unescaped script tag in question field")
	}
	// The injection relies on `"` and `>` to break out of context;
	// html.EscapeString must encode them so the raw `"><img` sequence is absent.
	if strings.Contains(doc2, `"><img`) {
		t.Error("XSS: unescaped attribute-breaking sequence in narrative field")
	}
	// Escaped versions must be present
	if !strings.Contains(doc2, "&lt;script&gt;") {
		t.Error("XSS: question should be HTML-escaped")
	}
}
