package engine

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// ReportGenerator produces the three FRACTURE result types from a completed simulation.
type ReportGenerator struct {
	llm LLMCaller // synthesis model (Claude Sonnet recommended)
}

// NewReportGenerator creates a ReportGenerator with the given synthesis LLM.
func NewReportGenerator(llm LLMCaller) *ReportGenerator {
	return &ReportGenerator{llm: llm}
}

// GenerateReport produces all six result types from a SimulationResult.
func (rg *ReportGenerator) GenerateReport(ctx context.Context, result *SimulationResult, question string) (*FullReport, error) {
	// Prepare context summary for the LLM
	summary := rg.buildSummary(result)

	probableFuture, err := rg.generateProbableFuture(ctx, question, summary)
	if err != nil {
		return nil, fmt.Errorf("probable future: %w", err)
	}

	tensionMap := rg.buildTensionMap(result)

	ruptureScenarios, err := rg.generateRuptureScenarios(ctx, question, summary, tensionMap)
	if err != nil {
		return nil, fmt.Errorf("rupture scenarios: %w", err)
	}

	coalitions, err := rg.generateCoalitions(ctx, question, summary)
	if err != nil {
		// Non-fatal: coalitions are bonus output
		coalitions = nil
	}

	ruptureTimeline, err := rg.generateRuptureTimeline(ctx, question, summary, ruptureScenarios)
	if err != nil {
		ruptureTimeline = nil
	}

	playbook, err := rg.generateActionPlaybook(ctx, question, summary, ruptureScenarios)
	if err != nil {
		playbook = nil
	}

	return &FullReport{
		SimulationID:     result.SimulationID,
		Question:         question,
		ProbableFuture:   probableFuture,
		TensionMap:       tensionMap,
		RuptureScenarios: ruptureScenarios,
		Coalitions:       coalitions,
		RuptureTimeline:  ruptureTimeline,
		ActionPlaybook:   playbook,
		FractureEvents:   result.FractureEvents,
		TotalTokens:      result.TotalTokens,
		DurationMs:       result.DurationMs,
		Watermark: Watermark{
			Tool:        "FRACTURE",
			Version:     "1.2.0",
			URL:         "https://github.com/mkvinicius/fracture",
			License:     "AGPL-3.0",
			GeneratedAt: time.Now().UTC().Format(time.RFC3339),
			Notice:      "Generated by FRACTURE v1.2.0 — Market Disruption Simulation Engine. Licensed under AGPL-3.0. https://github.com/mkvinicius/fracture",
		},
	}, nil
}

// RuptureTimelineEvent is a projected disruption event on the rupture timeline.
type RuptureTimelineEvent struct {
	Horizon     string  `json:"horizon"`
	RuleID      string  `json:"rule_id"`
	Description string  `json:"description"`
	Trigger     string  `json:"trigger"`
	Probability float64 `json:"probability"`
}

// FullReport is the complete output of a FRACTURE simulation.
type FullReport struct {
	SimulationID     string                 `json:"simulation_id"`
	Question         string                 `json:"question"`
	ProbableFuture   ProbableFuture         `json:"probable_future"`
	TensionMap       []TensionEntry         `json:"tension_map"`
	RuptureScenarios []RuptureScenario      `json:"rupture_scenarios"`
	Coalitions       []Coalition            `json:"coalitions,omitempty"`
	RuptureTimeline  []RuptureTimelineEvent `json:"rupture_timeline,omitempty"`
	ActionPlaybook   *ActionPlaybook        `json:"action_playbook,omitempty"`
	FractureEvents   []FractureEvent        `json:"fracture_events"`
	TotalTokens      int                    `json:"total_tokens"`
	DurationMs       int64                  `json:"duration_ms"`
	Watermark        Watermark              `json:"watermark"`
}

// Watermark identifies the tool that generated this report.
type Watermark struct {
	Tool      string `json:"tool"`       // "FRACTURE"
	Version   string `json:"version"`    // e.g. "1.1.0"
	URL       string `json:"url"`        // project URL
	License   string `json:"license"`    // "AGPL-3.0"
	GeneratedAt string `json:"generated_at"` // RFC3339 timestamp
	Notice    string `json:"notice"`     // human-readable attribution
}

// ProbableFuture describes the most likely evolution if no rules are broken.
type ProbableFuture struct {
	Narrative    string           `json:"narrative"`
	Timeline     []TimelineEntry  `json:"timeline"`
	Confidence   float64          `json:"confidence"`
	KeyAssumptions []string       `json:"key_assumptions"`
}

// TimelineEntry is a projected event at a specific time horizon.
type TimelineEntry struct {
	Horizon     string  `json:"horizon"`    // "6 months", "12 months", "24 months"
	Description string  `json:"description"`
	Confidence  float64 `json:"confidence"`
}

// TensionEntry represents a rule and its current tension level.
type TensionEntry struct {
	RuleID      string  `json:"rule_id"`
	Description string  `json:"description"`
	Domain      string  `json:"domain"`
	Tension     float64 `json:"tension"`
	Color       string  `json:"color"` // "green" | "yellow" | "orange" | "red"
}

// buildSummary creates a concise text summary of the simulation for the synthesis LLM.
func (rg *ReportGenerator) buildSummary(result *SimulationResult) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("Simulation ran %d rounds with %d total tokens.\n\n", len(result.Rounds), result.TotalTokens))

	if len(result.FractureEvents) > 0 {
		sb.WriteString(fmt.Sprintf("%d FRACTURE POINT(s) were triggered:\n", len(result.FractureEvents)))
		for _, fe := range result.FractureEvents {
			accepted := "REJECTED"
			if fe.Accepted {
				accepted = "ACCEPTED"
			}
			sb.WriteString(fmt.Sprintf("- Round %d: %s proposed changing rule '%s' → %s\n",
				fe.Round, fe.ProposedBy, fe.Proposal.OriginalRuleID, accepted))
			if fe.Accepted {
				sb.WriteString(fmt.Sprintf("  New rule: %s\n", fe.Proposal.NewDescription))
			}
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("No FRACTURE POINTs were triggered — the world remained stable.\n\n")
	}

	// Summarize last 5 rounds of notable actions
	sb.WriteString("Key agent observations from final rounds:\n")
	start := len(result.Rounds) - 5
	if start < 0 {
		start = 0
	}
	for _, rr := range result.Rounds[start:] {
		for _, action := range rr.Actions {
			if len(action.Text) > 20 {
				sb.WriteString(fmt.Sprintf("- [%s] %s\n", action.AgentID[:8], action.Text[:min(150, len(action.Text))]))
			}
		}
	}

	return sb.String()
}

// buildTensionMap converts the world's tension data into sorted TensionEntries.
func (rg *ReportGenerator) buildTensionMap(result *SimulationResult) []TensionEntry {
	var entries []TensionEntry
	for ruleID, tension := range result.TensionMap {
		rule, ok := result.FinalWorld.Rules[ruleID]
		if !ok || !rule.IsActive {
			continue
		}
		color := "green"
		switch {
		case tension >= 0.7:
			color = "red"
		case tension >= 0.5:
			color = "orange"
		case tension >= 0.3:
			color = "yellow"
		}
		entries = append(entries, TensionEntry{
			RuleID:      ruleID,
			Description: rule.Description,
			Domain:      string(rule.Domain),
			Tension:     tension,
			Color:       color,
		})
	}
	// Sort by tension descending
	for i := 0; i < len(entries); i++ {
		for j := i + 1; j < len(entries); j++ {
			if entries[j].Tension > entries[i].Tension {
				entries[i], entries[j] = entries[j], entries[i]
			}
		}
	}
	return entries
}

// extractJSON removes markdown code fences from LLM responses.
func extractJSON(raw string) string {
	// Remove ```json ... ``` or ``` ... ``` blocks
	raw = strings.TrimSpace(raw)
	if strings.HasPrefix(raw, "```") {
		// Find the first newline after the opening fence
		newline := strings.Index(raw, "\n")
		if newline != -1 {
			raw = raw[newline+1:]
		}
		// Remove closing fence
		if idx := strings.LastIndex(raw, "```"); idx != -1 {
			raw = raw[:idx]
		}
		raw = strings.TrimSpace(raw)
	}
	return raw
}

// generateProbableFuture calls the synthesis LLM to produce the narrative.
func (rg *ReportGenerator) generateProbableFuture(ctx context.Context, question, summary string) (ProbableFuture, error) {
	systemPrompt := `You are a strategic analyst synthesizing a market simulation.
Your task: produce a structured "Probable Future" report based on simulation results.
Be specific, concrete, and grounded in the simulation data.
Respond in JSON format only.`

	userPrompt := fmt.Sprintf(`Question asked: %s

Simulation summary:
%s

Produce a Probable Future report in this exact JSON format:
{
  "narrative": "2-3 paragraph narrative of the most likely future if no rules change",
  "timeline": [
    {"horizon": "6 months", "description": "...", "confidence": 0.8},
    {"horizon": "12 months", "description": "...", "confidence": 0.7},
    {"horizon": "24 months", "description": "...", "confidence": 0.6}
  ],
  "confidence": 0.75,
  "key_assumptions": ["assumption 1", "assumption 2", "assumption 3"]
}`, question, summary)

	raw, _, err := rg.llm.Call(ctx, systemPrompt, userPrompt, 800)
	if err != nil {
		return ProbableFuture{}, err
	}

	clean := extractJSON(raw)
	var result ProbableFuture
	if err := json.Unmarshal([]byte(clean), &result); err != nil {
		result.Narrative = raw
		result.Confidence = 0.5
	}
	return result, nil
}

// generateRuptureScenarios calls the synthesis LLM to produce the top 3 rupture scenarios.
func (rg *ReportGenerator) generateRuptureScenarios(ctx context.Context, question, summary string, tensionMap []TensionEntry) ([]RuptureScenario, error) {
	// Build tension context
	var tensionLines []string
	for i, t := range tensionMap {
		if i >= 5 {
			break
		}
		tensionLines = append(tensionLines, fmt.Sprintf("- %s (tension: %.2f, domain: %s)", t.Description, t.Tension, t.Domain))
	}

	systemPrompt := `You are a strategic disruption analyst.
Your task: identify the 3 most likely rupture scenarios — moments where fundamental market rules could be rewritten.
For each scenario, explain who breaks the rule, how it happens, the impact, and crucially: how the company could be FIRST to break it themselves.
Respond in JSON format only.`

	userPrompt := fmt.Sprintf(`Question asked: %s

Simulation summary:
%s

Most tense rules (highest disruption potential):
%s

Produce exactly 3 rupture scenarios in this JSON format:
[
  {
    "rule_id": "...",
    "rule_description": "The current rule that could be broken",
    "probability": 0.65,
    "who_breaks": "Which archetype/player is most likely to break this rule",
    "how_it_happens": "Specific mechanism — what triggers the change and how it unfolds",
    "impact_on_company": "Direct impact on the company asking the question",
    "how_to_be_first": "Concrete steps the company could take to break this rule themselves before a competitor does"
  }
]`, question, summary, strings.Join(tensionLines, "\n"))

	raw, _, err := rg.llm.Call(ctx, systemPrompt, userPrompt, 1200)
	if err != nil {
		return nil, err
	}

	clean := extractJSON(raw)
	var scenarios []RuptureScenario
	if err := json.Unmarshal([]byte(clean), &scenarios); err != nil {
		return []RuptureScenario{{
			RuleDescription: "Analysis unavailable",
			HowItHappens:    raw,
		}}, nil
	}
	return scenarios, nil
}

// generateCoalitions identifies agent alliances from simulation data.
func (rg *ReportGenerator) generateCoalitions(ctx context.Context, question, summary string) ([]Coalition, error) {
	systemPrompt := `You are a strategic analyst identifying hidden alliances in a market simulation.
Based on the simulation data, identify 2-4 coalitions of agents that aligned around shared interests.
Respond in JSON format only.`

	userPrompt := fmt.Sprintf(`Question: %s

Simulation summary:
%s

Identify 2-4 coalitions in this JSON format:
[
  {
    "name": "Coalition name",
    "agent_names": ["Agent 1", "Agent 2"],
    "shared_goal": "What they want together",
    "strength": 0.75,
    "is_disruptive": false
  }
]`, question, summary)

	raw, _, err := rg.llm.Call(ctx, systemPrompt, userPrompt, 600)
	if err != nil {
		return nil, err
	}

	clean := extractJSON(raw)
	var coalitions []Coalition
	if err := json.Unmarshal([]byte(clean), &coalitions); err != nil {
		return nil, err
	}
	return coalitions, nil
}

// generateRuptureTimeline produces a chronological map of when ruptures are likely to occur.
func (rg *ReportGenerator) generateRuptureTimeline(ctx context.Context, question, summary string, scenarios []RuptureScenario) ([]RuptureTimelineEvent, error) {
	var scenarioLines []string
	for _, s := range scenarios {
		scenarioLines = append(scenarioLines, fmt.Sprintf("- %s (probability: %.0f%%)", s.RuleDescription, s.Probability*100))
	}

	systemPrompt := `You are a strategic foresight analyst building a disruption timeline.
Map each rupture scenario to a specific time horizon with a trigger event.
Respond in JSON format only.`

	userPrompt := fmt.Sprintf(`Question: %s

Rupture scenarios:
%s

Simulation summary:
%s

Produce a timeline in this JSON format:
[
  {
    "horizon": "3 months",
    "rule_id": "...",
    "description": "What changes",
    "trigger": "The specific event that triggers this rupture",
    "probability": 0.4
  }
]`, question, strings.Join(scenarioLines, "\n"), summary)

	raw, _, err := rg.llm.Call(ctx, systemPrompt, userPrompt, 700)
	if err != nil {
		return nil, err
	}

	clean := extractJSON(raw)
	var timeline []RuptureTimelineEvent
	if err := json.Unmarshal([]byte(clean), &timeline); err != nil {
		return nil, err
	}
	return timeline, nil
}

// generateActionPlaybook produces the strategic playbook for the user.
func (rg *ReportGenerator) generateActionPlaybook(ctx context.Context, question, summary string, scenarios []RuptureScenario) (*ActionPlaybook, error) {
	var howToBeFirst []string
	for _, s := range scenarios {
		if s.HowToBeFirst != "" {
			howToBeFirst = append(howToBeFirst, s.HowToBeFirst)
		}
	}

	systemPrompt := `You are a strategic advisor creating an action playbook for a company.
Based on the simulation results, provide concrete, actionable recommendations.
Be specific — avoid generic advice. Respond in JSON format only.`

	userPrompt := fmt.Sprintf(`Question: %s

Simulation summary:
%s

How-to-be-first insights from rupture scenarios:
%s

Produce an action playbook in this exact JSON format:
{
  "horizon_90_days": ["Action 1", "Action 2", "Action 3"],
  "horizon_1_year": ["Action 1", "Action 2", "Action 3"],
  "horizon_3_years": ["Action 1", "Action 2"],
  "quick_wins": ["Quick win 1", "Quick win 2"],
  "critical_risks": ["Risk 1", "Risk 2", "Risk 3"]
}`, question, summary, strings.Join(howToBeFirst, "\n"))

	raw, _, err := rg.llm.Call(ctx, systemPrompt, userPrompt, 800)
	if err != nil {
		return nil, err
	}

	clean := extractJSON(raw)
	var playbook ActionPlaybook
	if err := json.Unmarshal([]byte(clean), &playbook); err != nil {
		return nil, err
	}
	return &playbook, nil
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
